# Generated by Django 5.0.14 on 2025-12-25 22:41

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('start_seconds', models.IntegerField(blank=True, null=True)),
                ('end_seconds', models.IntegerField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name shown to users. Should match the real public figure.', max_length=200, verbose_name='Mentor name')),
                ('slug', models.SlugField(help_text='Unique identifier for the mentor, used in URLs.', max_length=200, unique=True)),
                ('primary_language', models.CharField(default='en', max_length=50)),
                ('bio', models.TextField(blank=True, help_text='Short biography of the mentor.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512, validators=[django.core.validators.MinLengthValidator(5, 'Title must be at least 5 characters long.')])),
                ('youtube_video_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('fetched', 'Transcript fetched'), ('chunked', 'Chunked'), ('embedded', 'Embedded'), ('ready', 'Ready'), ('failed', 'Failed')], default='new', max_length=20)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='articles.mentor')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='contentchunk',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='articles.videocontent'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['mentor', 'youtube_video_id'], name='articles_vi_mentor__a36261_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['status'], name='articles_vi_status_dd3320_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videocontent',
            unique_together={('mentor', 'youtube_video_id')},
        ),
        migrations.AddIndex(
            model_name='contentchunk',
            index=models.Index(fields=['video', 'chunk_index'], name='articles_co_video_i_5639fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentchunk',
            unique_together={('video', 'chunk_index')},
        ),
    ]
