# Generated by Django 5.0.14 on 2025-12-25 22:50

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_url'),
    ]

    operations = [
        CreateExtension('vector'),
    ]
