# Generated by Django 5.0.14 on 2025-12-25 22:50

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_contentchunk_mentor_videocontent_delete_article_and_more'),
    ]

    operations = [
        CreateExtension('vector'),
    ]
